version: '3.8'

services:
  # 你的 Python MCP Server
  mcp-server:
    image: python:3.14.2-alpine3.23
    container_name: LennySkills
    working_dir: /app
    volumes:
      - .:/app 
      - /app/.venv
    environment:
      - UV_PROJECT_ENVIRONMENT=/app/.venv
    ports:
      - "8001:8001"
    command: >
      sh -c "pip install uv && 
             uv sync && 
             .venv/bin/python MCPserver.py"

